### DISCUSSION TITLE
How do you setup support for SRV dns domains?

### DISCUSSION THREAD

**Discussion by momomo** [shadowsocks/shadowsocks-rust#890] [Q&A]
I found this: 

https://github.com/shadowsocks/libudns/blob/master/udns_rr_srv.c

But so far I am way too unfamiliar with anything to figure out how to use it. 

I have downloaded the mac version v.1.5.0 of **shadowsocks rust**. 

I am starting the server, starting the local with the following shared config: 

```
{
    "server": "192.168.0.175",
    "server_port": 50001,
    
    "local_address": "127.0.0.1",
    "local_port": 50001,
    
    "password": "mypassword",
    "timeout": 900,
    "method": "aes-256-gcm"
}
```

This alone is not working but I am using then in turn **https://github.com/sipt/shuttle** to redirect all traffic to the local one. 
The config for **shuttle** is: 

```
ver: v1.0.1
General:
  loglevel: "debug"
  dns-server:
    - "192.168.0.175"
    - "114.114.114.114"
    - "223.5.5.5"
  http-port: "8080"
  http-interface: "0.0.0.0"
  socks-port: "8081"
  socks-interface: "0.0.0.0"
  controller-port: "8082"
  controller-interface: "0.0.0.0"
Proxy:
  "socks": ["socks", "127.0.0.1", "50001"]
  "socks-tls": ["socks-tls", "127.0.0.1", "50001", "skip-verify"]
  "socks-auth": ["socks", "127.0.0.1", "50001", "chacha20poly1305", "your-password"]
  "socks-tls-auth": ["socks-tls", "127.0.0.1", "50001", "skip-verify", "chacha20poly1305", "your-password"]
Proxy-Group:
  "a": ["select", "socks"]
  "n": ["select", "DIRECT"]
Local-DNS:
  - ["DOMAIN", "192.168.0.175", "static", "127.0.0.1"]
Http-Map:
  Req-Map:
    - url-rex: "^http://www.example.aaa"
      type: "UPDATE"
      items:
        - ["URL", "", "http://www.example.bbb"]
        - ["HEADER", "test_header", "vvvvvvvv"]
    - url-rex: "^http://www.mock.ccc"
      type: "MOCK"
      items:
        - ["STATUS", "", "500"]
        - ["HEADER", "Content-Type", "application/json"]
        - ["BODY", "", "mock.json"]
  Resp-Map:
    - url-rex: "^http://www.redirect_to_github.com"
      type: "UPDATE"
      items:
        - ["STATUS", "", "301"]
        - ["HEADER", "Location", "https://github.com"]
MITM:
  rules: ["*.baidu.com"]
  ca: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzekNDQWNlZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREF4TVJBd0RnWURWUVFLRXdkVGFIVjAKZEd4bE1SMHdHd1lEVlFRREV4UlRhSFYwZEd4bElFZGxibVZ5WVhSbFpDQkRRVEFlRncweE9EQTRNVEF4TVRRNApOVGRhRncweU16QTRNVEF4TVRRNE5UZGFNREV4RURBT0JnTlZCQW9UQjFOb2RYUjBiR1V4SFRBYkJnTlZCQU1UCkZGTm9kWFIwYkdVZ1IyVnVaWEpoZEdWa0lFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUFyUVF5aU90T1ZSZEpqOHJPb2k2LzhjSkdiSmtiVnVYOTYyRTlweWFyTy9GZWhoL1R5c3d4SHJFRgovcW1IUGpvcXBjMjA5VXU2RHNVRk1HMjRXTGJuV05JMElWY3U1YURuVWVCa204ZnFEa25qZUh3cXQveEJ1b1FnCnhNbWROQTRDNjd3alpWL0VlUldpVTlrbXhtK2k2cEFRcXR3Y0Y3N3B6TDRuZUdLbFRTMGdadlVXWng3TEZDaS8KbDBWZzBFNHZDckNWeUpncUx6Y2UrdkoxUml5U0hFYVRSdVo1SUZYbU84ZmYwd0hNNGlsT3kyVHRnTFh0TjdMSApHRDFEOFc1TS9qemllVzQvQVhMeURYUEVKeTZ6S2lOOVU4K2FJbUNUcHBydnl1Q2FlMXRMeFdmcWcwWkVYYy9VCnpNcktjcXBBb2Noc1hLd2dINm5nU0VkMHU0V1NrUUlEQVFBQm93SXdBREFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQVAvSVVWdDFVbXAxVkFzdVJXazRLdzVUamFlbUsvb1hQVkFBdkVyOEJaQS9IWXpsdU1TUTgrSWc1NlR2agpxNnJzMFpLU002K0t1TERyeEhsZHcxelJsUTFCYlRPMkVHNHdGSEZ5RHA3eGswbWs1TXAvbDBNd1ZpWjlDbkFGCnFMVDRtc1MyRjlzREM2MHN5M3lrd1g1OWtIcS9tTWIyNENaRnhGdVR6N3dpNmdlN0t1YlM3dDI3WGlOTHNZSlMKMG11N2MveFZLcUVTd21jNWdVa2M2OTVzdEczZExxZDJBenovZWZSOWZSREJIUEhlcForYXZNKzBkekRPdzdNKwpZOVNFeFl3K3lQUE1kUXkxZ3ZOTmFRait1LzhrTm9odW94cEladmJ2N1BSckE0bTVZblVOcm1Va0dFQi8vU0FnClc3cTVuSXlQdWo0d08xSW5SeU1mZHNyOFdnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo"
  key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBclFReWlPdE9WUmRKajhyT29pNi84Y0pHYkprYlZ1WDk2MkU5cHlhck8vRmVoaC9UCnlzd3hIckVGL3FtSFBqb3FwYzIwOVV1NkRzVUZNRzI0V0xibldOSTBJVmN1NWFEblVlQmttOGZxRGtuamVId3EKdC94QnVvUWd4TW1kTkE0QzY3d2paVi9FZVJXaVU5a214bStpNnBBUXF0d2NGNzdwekw0bmVHS2xUUzBnWnZVVwpaeDdMRkNpL2wwVmcwRTR2Q3JDVnlKZ3FMemNlK3ZKMVJpeVNIRWFUUnVaNUlGWG1POGZmMHdITTRpbE95MlR0CmdMWHRON0xIR0QxRDhXNU0vanppZVc0L0FYTHlEWFBFSnk2ektpTjlVOCthSW1DVHBwcnZ5dUNhZTF0THhXZnEKZzBaRVhjL1V6TXJLY3FwQW9jaHNYS3dnSDZuZ1NFZDB1NFdTa1FJREFRQUJBb0lCQVFDc2V3QytDb2Fld1ladQpPT3BpT0dUVjZLMDRXakl0SVQ5UHhqTW1UYUJyTTZiZDR5REtqV0Z5alZ2Q2t0TG1zQ29QL05DbnNZU2NjTUZKCmxEZ3hDTFg5a0NDMEZDd0djNi9ucWVIaWd4dk1mdENzTG15UDJvVFVJaUJnemZWUURaL1B6bEVqSUtQSGFrL1gKY3lYNnNSUWk3dGdPM1R1TVdLRFBvY25MYzl3QzRKUDdHL2UxK1R0NEFZU0VneHRicGhsdnN2QW50d2ZlSm1FcgpqbDUvQ0hRTFp1UDB3ME5lWU5HMHVud1FJMnQ4ckZwaWdBWXFadDNQZnpXY25nTkkvUnFIVklUcVRoSmV1dDV6CnFrNmovaW9LZGlnUjlCeitDNzdJTVZGOU5VOXVMZE5LdHBZRUUvSkgveVNORGpRM1ZpV3VnK2VrWnlicVIzcU8KM2RudlJCbWhBb0dCQU1wblBpVnVTMmdFNUdveWxIaHZIUjNHOG9nY2hWTklSSW51bXhMcVhSb3g3MHFKOXFGOQorTThRTVZMVWV2RHpROFhMb0RvOGI4dGNuWm1rSitLRzRZRjVCYjV1Q1FPbDBZK1M3dStpSFlscjhiNk9jS2dJCjBZdWVEQzBwMkdRQUdoZ0R6U01WeGZ2MElZTlhnbDdTUk1MTHVqNmU5V09OekcxYWZnZElDaGI5QW9HQkFOclUKMXltVGpJZTA4aFAzQ01IVUJEYkpqVU5Sd0dKQnVmY052UEp5R2h1N3Y1V3QvdFZVNThpRis3QUJoNzhCK3NDdQoybkhDS0c0MDl4U1lwSnFHbkl4dkFKQzhWZHlPQmVpZDArNmhYckRpTS9YODFJWHVDL1hJTitSbko3NjVST0V2CjZmRXB4T0F0ZldaUGllSUNSRnFycFNDeEcvOG0rTFdhRFBIczVVQWxBb0dBSW11R1JRVkpxNG5SY2tIaHY4MWQKalRmTS9OcWt6YkhuZmZGbXk4T3hTNGdjWW5ldHltN0t4aVBCejQwMHp3Ny9nbjZMWS92dEl3OC8rZVhScHBNNwpmREloaU8zYmVKUlZXKzRuMWZhaXdVRHJIblhJc0xxM0wrQVR3QVp5dHliUlNTNDBUM2dmY0NabklKZmNJdFh0ClBaYzV0L1orVW96RnEvOE1tWjVsb04wQ2dZQVk5TUQ4K3RqQitUN0tUQmZ4a3U1UUdUaEUveVBEa045V2IzaW0KNWFCWW5WYkNDUy9Rd0hnV2hFRXAxMkxWdzdJSEcybktJMnhjOVNsZ2JmQUh0MlpQRmJHb3ovR3l6M2VaQ2JiTAp0aGVJY0tPZ1lBOFVud3M2SW5WTlZQNVJYK3VkQ3N2Uk53USsxTEZDWTd2RHpLSmkvTVErTURTVEtxeWVlVTBVCm9nR2JDUUtCZ1FDUWFyV2tJZlBSMFQycjFaUGpVWEhjYVBaN2NZMVExcXp0UXFSQXE2OTlhcVUzaUFQbVlxSTIKMkJ3aE1kS296aVZ5cldpWWJzc005MCtBY1duSzZIN0VZZlc4TXNzcS90MHV3VU9PN2xmakdIVmhKZFltQjlTZQo5TmhSOVF5OHFWa2NXbk9FUzQxYXFnYWsza05BTTJOT05TRUZnbGk4MDNhYzcxbHZWNFVBbHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo"
Rule:
  - ["FINAL", "", "a", ""]
```

When I launch shuttle, with ./shuttle path-to-above.config.yaml 

most dns queries seems to work and is tunneled through the shadowsocks local to the shadowsocks server/laptop and I can visit all kinds of things. 

However, when hitting **SRV domains** I am unable to get them to be resolved. 

I found the lib (https://github.com/shadowsocks/libudns/blob/master/udns_rr_srv.c) but **how do I use** it with shadowsocks? 

I **also struggle** to figure out the configuration for shadowsocks as the documenation is not 100% solid. 

For instance, how do I install other plugins such as the **"v2ray" plugin**? No info on how. Configuration is filled with  that use case but it is not in the mac binaries.
