### ISSUE TITLE
shadowsocks on kubernetes with traefik ingress

### ISSUE THREAD

**Issue by waterdrop01** [shadowsocks/shadowsocks-rust#1067]
Hello,

So I deployed ```shadowsocks-rust``` on kubernetes thanks to the [manifest](https://github.com/shadowsocks/shadowsocks-rust/tree/master/k8s) (big up to @realies).

First, let's start with what is working:

- Using local port forward ```kubectl  port-forward pod/shadowsocks-rust-6ff96bd5dc-qnppw  8388:8388```

And then routing my traffic to `127.0.0.1:8388` works!

However, when trying to connect using a domain name pointing to my Traefik ingress, it doesn't work. 

Here is my ingress definition:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shadowsocks-rust
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`shadowsocks.domain.me`)
      services:
        - name: shadowsocks-rust
          port: 8388   <--- I use 8388 instead of the default 80 
  tls:
    certResolver: le
```
And websecure refers to this Traefik conf:
```
--entrypoints.websecure.address=:8443/tcp
```

Any idea on how to tell traefik to correctly route my sslocal traffic to `shadowsocks-rust` running in k8s, directly? (without having to `kubectl  port-forward`)

Thanks a lot!
