### ISSUE TITLE
Unable to start the server on arch linux

### ISSUE THREAD

**Issue by ssddOnTop** [shadowsocks/shadowsocks-rust#1347]
I initially tried it with docker compose (made a docker compose file with the commands in readme. 

My `docker-compose.yml`

```yml
version: '3'

services:
  ssserver-rust:
    container_name: ssserver-rust
    image: ghcr.io/shadowsocks/ssserver-rust:v1.17.0@sha256:57c99fc7df04daacc3d968d7b9df0a1223e18bdc69a3a6fd403cacc138f1d4b4
    restart: always
    ports:
      - "83:8388/tcp"
      - "83:8388/udp"
    volumes:
      - ./config.json:/etc/shadowsocks-rust/config.json
```

initially the image I used was `ghcr.io/shadowsocks/ssserver-rust:latest`, then I saw this in releases and started using this image

I also cloned the repo and compiled it myself.

but all the steps throw same error `ssserver-rust  | server aborted with Address not available (os error 99)`
I checked that the required port is not used by any other service (tried with 8388 and 83)

<img width="410" alt="image" src="https://github.com/shadowsocks/shadowsocks-rust/assets/62684960/5a586d02-eb14-4d32-bd3b-589dc9c49766">

here's my `config.json`

```json
{
    "server": "mail.ssdd.dev",
    "server_port": 83,
    "password": "<key generated by ssservice genkey -m aes-128-gcm>",
    "method": "aes-256-gcm",
}
```
