### ISSUE TITLE
Default log4rs.yaml is not rolling

### ISSUE THREAD

**Issue by aoslee** [shadowsocks/shadowsocks-rust#412]
Hi:
   I used default log4rs.yaml, but  log is not rolling when file is 10m.I modify debug to trace only.

 start command:
/usr/local/bin/sslocal -d -c /root/ss/local_config.json   --log-config /root/ss/local_log4rs.yaml --acl /root/ss/local_acl.acl --daemonize-pid  /root/ss/sslocalid.pid 
os: centos8.2
build version: 0b9ad113ad3a3cb80ddad5ecdd5b52e11e65e18d
my log4rs.yaml
```
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {h({l}):<5} {m}{n}"
  file:
    kind: rolling_file
    path: shadowsocks.log
    encoder:
      kind: pattern
      pattern: "{d} {h({l}):<5} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: shadowsocks.{}.log
        count: 5
root:
  level: trace
  appenders:
    - stdout
    - file
```

**Comment by zonyitoo** [comment]
That's interesting. I tested on my macOS laptop, and it works fine.

**Comment by aoslee** [comment]
Hi:
 @zonyitoo , Thanks for reply.
Yes，you are right.  Rolling is ok, but rolling log path is  relative.That is obscure that 'path' is execution path and 'pattern' is '/'(root) path.  https://github.com/estk/log4rs/issues/112
so modify log4rs.yaml for understanding easy.
```
 refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {h({l}):<5} {m}{n}"
  file:
    kind: rolling_file
    path: /root/ss/shadowsocks.log
    encoder:
      kind: pattern
      pattern: "{d} {h({l}):<5} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: /root/ss/shadowsocks.{}.log
        count: 5
root:
  level: trace
  appenders:
    - stdout
    - file
   ```
