### ISSUE TITLE
本地访问服务端能访问的内网访问不了

### ISSUE THREAD

**Issue by shangtianfei** [shadowsocks/shadowsocks-rust#449]
我使用docker搭建了一个服务，在本地浏览器访问 http://192.168.131.85:8989/#/ 打不开，这个网址在服务端使用curl是有响应的
我的docker-compose.yml
```
version: '3'
services:
  shadowsocks-server:
    image: setonegoodfamily/ssr:1.03.10
    container_name: shadowsocks-server
    ports:
     - "39008:39008"
    restart: always
    environment: 
      server: 0.0.0.0
      server_port: 39008
      password: "Abc@1234"
      method: "aes-256-cfb"
      timeout: 600
```
